version: '3.8'

services:
  postgres:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: prisma
      POSTGRES_USER: prisma
      POSTGRES_DB: prisma
    ports:
      - 5432:5432

  supertokens:
    depends_on:
      postgres:
        condition: service_healthy
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    container_name: supertokens
    restart: always
    environment:
      POSTGRESQL_PASSWORD: prisma
      POSTGRESQL_USER: prisma
      POSTGRESQL_HOST: postgres
      POSTGRESQL_PORT: 5432
      POSTGRESQL_DATABASE_NAME: supertokens
    ports:
      - 3567:3567

volumes:
  pgdata:
