version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: prisma
      POSTGRES_USER: prisma
      POSTGRES_DB: prisma
    ports:
      - 5432:5432

  webapp:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: webapp
    volumes:
      - /usr/src/node_modules
      - /usr/src/packages/config/node_modules
      - /usr/src/packages/schemas/node_modules
      - /usr/src/packages/ui/node_modules
      - /usr/src/apps/api/node_modules
      - /usr/src/apps/web/node_modules
      - .:/usr/src
    ports:
      - 5000:5000
      - 3000:3000

volumes:
  pgdata:
