version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: prisma
      POSTGRES_USER: prisma
      POSTGRES_DB: prisma
    ports:
      - 5432:5432

volumes:
  pgdata:
